# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         false
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            92c6c2b698f534f650c78bb52a60d6cf66fd3575

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true

    i18n: on

    default_culture:  es_ES

    standard_helpers: [Partial, Cache, I18N]

    enabled_modules: [default, sfGuardAuth, sfGuardUser, sfAsset, sfAdminDash, gallery, photos, portfolio]

  .actions:
    login_module: sfGuardAuth
    login_action: signin
