<?php

/**
 * Item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    rugby
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Item extends BaseItem
{

  public function getTypeTitle()
  {
    // devuelve el nombre del tipo del articulo
    return $this->ItemType->name;
  }

  public function saveClick(Item $item)
  {
    // guardamos un click mas al articulo
    $query = Doctrine_Core::getTable('Item')->updateClicks($item);
  }

  // salvamos el articulo seteandole el usuario logueado
  public function save(Doctrine_Connection $conn = null)
    {
      $conn = $conn ? $conn : Doctrine_Manager::getInstance()->getCurrentConnection();
      $conn->beginTransaction();
      try
      {
        if (isset($_SESSION['symfony/user/sfUser/attributes']['sfGuardSecurityUser']['user_id'])) {
           $this->setSfGuardUserId($_SESSION['symfony/user/sfUser/attributes']['sfGuardSecurityUser']['user_id']);   
        }        
            
        $ret = parent::save($conn);
     
        $conn->commit();
      
        return $ret;
      }
      catch (Exception $e)
      {
        $conn->rollBack();
        throw $e;
      }
    }

}
