<?php

/**
 * MatchTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MatchTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MatchTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Match');
    }

    // obtiene todos los partidos ordenados por fecha
    public function getMatches()
    {
      $q = $this->createQuery('m')
      ->orderBy('m.date');
      
      return $q->execute();
    }

    public function getMatchesByYear($year){
      $q = $this->createQuery('m')
      ->Where('YEAR(m.date) >= ?',$year)
      ->orderBy('m.date');
      
      return $q->execute();
    }

    public function getMatchesBySearch($search)
    {
      $q = $this->createQuery('m')
      ->Where('((m.team_one like ?) OR (m.team_two like ?))', array($search,$search))
      ->andWhere('m.date >= now()')
      ->orderBy('m.date');
      
      return $q->execute();
    }

}
