<?php

/**
 * MemberTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MemberTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MemberTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Member');
    }

    // devuelve los miembros segun el member_type_id recibido por parametro
    public function getMembersByType($type_id = null)
    {
      $q = $this->createQuery('i')
      ->where('i.member_type_id=?', $type_id);
      
      return $q->execute();
    }

    public function getMembersBySearch($search)
    {
      $q = $this->createQuery('i')
      ->where('i.name like ?', $search)
      ->orWhere('i.email like ?',$search)
      ->orWhere('i.category like ?',$search);
      
      return $q->execute();
    }

}
