<?php

/**
 * Member
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    rugby
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Member extends BaseMember
{
  public function getMemberTypeTitle(){
    // devuelve el nombre del tipo del miembro
    return $this->getMemberType()->getName();
  }
    
}
