<?php

/**
 * StuffTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StuffTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StuffTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Stuff');
    }
}