# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Ensenada Rugby Club | Sitio Web
    description:  Sitio Web de Ensenada Rugby Club
    keywords:     rugby, rugby club, ensenada, la plata
    language:     es
    author:       Frank, Tinchox
    robots:       index, follow

  stylesheets:    []

  javascripts:    [jquery-1.5.1.min.js,setupSearch.js]

  has_layout:     true
  layout:         layout

  components:
    menu_news:    [menu, menuNews]
    menu_events:  [menu, menuEvents]
    site_name:    [config, set]
    site_enabled: [config, site]
    site_style:   [config, style]
