---
detect_relations: true
options:
  collate: latin1_swedish_ci
  charset: latin1
  type: InnoDB

detect_relations: true
options:
  charset: latin1
  type: InnoDB

Item:
  tableName: items
  actAs: 
    Timestampable:
      created:
        name: created_at
        type: date
        format: Y-m-d
      updated:
        name: updated_at
        type: date
        format: Y-m-d
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
      autoincrement: true
    title:
      type: string(100)
      notnull: true
      unique: true
    short_description:
      type: string(150)
      notnull: true
    long_description:
      type: clob(65535)
      notnull: true
    item_type_id:
      type: integer(4)
      default: null
    rss:
      type: boolean
      notnull: true
      default: 0
    sf_guard_user_id:
      type: integer(8)
      default: null
    click:
      type: integer(8)
      notnull: true
      default: '0'
  indexes:
    item_type_id_idx:
      fields: [item_type_id]
  options:
    charset: latin1
    type: MyISAM

ItemType:
  tableName: itemtypes
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
      autoincrement: true
    name:
      type: string(45)
      notnull: true
      unique: true
  options:
    charset: latin1
    type: MyISAM

Match:
  tableName: matches
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
      autoincrement: true
    team_one:
      type: string(45)
      notnull: true
    team_two:
      type: string(45)
      notnull: true
    date: date
  options:
    charset: latin1
    type: MyISAM

Stuff:
  tableName: stuffs
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
      autoincrement: true
    name_club:
      type: string(100)
      notnull: true
    address:
      type: string(255)
      notnull: true
    telephone:
      type: string(50)
      notnull: true
    email:
      type: string(50)
      notnull: true
    description:
      type: clob(65535)
      notnull: true
    latitud:
      type: string(20)
    longitud:
      type: string(20)
    story:
      type: string(8192)
      notnull: true
    rules:
      type: clob(65535)
      notnull: true
    contact_us:
      type: string(65535)
      notnull: true
  options:
    charset: latin1
    type: MyISAM

Member:
  tableName: members
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
      unique: true
    telephone:
      type: string(50)
    celphone:
      type: string(50)
    email:
      type: string(50)
    birthday:
      type: timestamp
    category:
      type: string(10)
    url_picture:
      type: string(512)
    member_type_id:
      type: integer(4)
      notnull: true
  indexes:
    member_type_id_idx:
      fields: [member_type_id]
  options:
    charset: latin1
    type: MyISAM

MemberType:
  tableName: membertypes
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
      autoincrement: true
    name:
      type: string(45)
      notnull: true
  options:
    charset: latin1
    type: MyISAM

Config:
  tableName: configs
  columns:
    id:
      type: integer(4)
      primary: true
      notnull: true
      autoincrement: true
    title:
      type: string(255)
      notnull: true  
    enabled:
      type: boolean
      notnull: true
      default: 1
    message:
      type: string(255)
      notnull: true
    pagination:
      type: integer(4)
      notnull: true
    style:
      type: enum
      values: ['default',tema2]
      default: 'default'
      notnull: true 
  options:
    charset: latin1
    type: MyISAM      

